# Use Node.js for production
FROM node:23-alpine3.20 as dev

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./

RUN npm install 


# Copy the rest of the application
COPY . .

# Build the React app
RUN npm run build

# Install NGINX to serve the production build
FROM nginx:alpine

# Copy the React build into NGINX’s HTML directory
COPY --from=0 /app/build /usr/share/nginx/html

# Expose the port NGINX will run on
EXPOSE 80

# Run NGINX to serve the app
CMD ["nginx", "-g", "daemon off;"]
