# Use Node.js for development
FROM node:25-alpine3.22 AS development

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install 

# Copy the rest of the application
COPY . .

# Expose the port that the development server will run on
EXPOSE 5173

# Run the development server
CMD ["npm", "run", "dev"]