
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "5173:5173"           # React dev server port
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app       # hot reload
      - /app/node_modules     # prevent mounting host's node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8000:8000"           # Node/Express dev port
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app        # hot reload
    depends_on:
      - postgres
      - redis
  # or whatever starts your backend dev server

  postgres:
    image: postgres:alpine
    container_name: pgdata
    restart: always
    ports:
      - "5433:5432"            # host:container
    environment:
      POSTGRES_DB: library_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: r33w@z@123
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"           # host:container
    command: redis-server --appendonly yes

volumes:
  pgdata:
