version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "5713:80"
    depends_on:
      - backend

    env_file:
      - ./frontend/.env
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist DB data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
