version: "3.8"

services:
  frontend:
    image: r33waz/library-frontend:v3
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./frontend.env
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    restart: always

  backend:
    image: r33waz/library-backend:v3
    ports:
      - "8000:8000"
    env_file:
      - ./backend.env
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: yourdb
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata:
