
FROM node:23-alpine

WORKDIR /app

# Copy only necessary build artifacts
COPY package.json package-lock.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 8000

CMD ["node", "dist/server.js"]
