import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1766382307459 implements MigrationInterface {
    name = 'AutoMigration1766382307459'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "category" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "slug" character varying NOT NULL, CONSTRAINT "UQ_23c05c292c439d77b0de816b500" UNIQUE ("name"), CONSTRAINT "UQ_cb73208f151aa71cdd78f662d70" UNIQUE ("slug"), CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genre" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "slug" character varying NOT NULL, CONSTRAINT "UQ_dd8cd9e50dd049656e4be1f7e8c" UNIQUE ("name"), CONSTRAINT "UQ_8fc42c0cf741b5006b5ffd12f24" UNIQUE ("slug"), CONSTRAINT "PK_0285d4f1655d080cfcf7d1ab141" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."library_emp_role_enum" AS ENUM('SUDO_ADMIN', 'ADMIN', 'USER', 'STUDENT', 'LIBRARY_EMP', 'LIBRARY_ADMIN')`);
        await queryRunner.query(`CREATE TABLE "library_emp" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "first_name" character varying NOT NULL, "middle_name" character varying, "last_name" character varying NOT NULL, "phone_number" character varying, "role" "public"."library_emp_role_enum" NOT NULL DEFAULT 'LIBRARY_EMP', "city" character varying NOT NULL, "street" character varying NOT NULL, "state" character varying NOT NULL, "libraryId" uuid, CONSTRAINT "PK_32980e25b6f098a8fba613350df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_request" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "requested_role" character varying NOT NULL, "status" character varying NOT NULL, "reason" character varying NOT NULL, "userId" uuid, CONSTRAINT "PK_56e5c87e0e09b2416e398992a88" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('SUDO_ADMIN', 'ADMIN', 'USER', 'STUDENT', 'LIBRARY_EMP', 'LIBRARY_ADMIN')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "first_name" character varying NOT NULL, "middle_name" character varying, "last_name" character varying NOT NULL, "phone_number" character varying, "university_id" character varying, "role" "public"."user_role_enum" NOT NULL DEFAULT 'USER', CONSTRAINT "UQ_1518391a178a27840edf478c7b9" UNIQUE ("university_id"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."media_mediatype_enum" AS ENUM('PROFILE', 'UNIVERSITY_CARD', 'BOOK', 'COVER_IMAGE', 'GENRE_PIC', 'CATEGORY_PIC', 'EMPLOYEE_CONTRACT', 'EMPLOYEE_PAN', 'EMPLOYEE_CITIZENSHIP')`);
        await queryRunner.query(`CREATE TABLE "media" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying NOT NULL, "name" character varying NOT NULL, "path" character varying NOT NULL, "mediaType" "public"."media_mediatype_enum", "bookCoverImageId" uuid, "profileId" uuid, "universityCardId" uuid, "adminProfileId" uuid, "libraryProfileId" uuid, "employeePicId" uuid, "employeePanId" uuid, "employeeCitizenshipId" uuid, "genreId" uuid, "categoryId" uuid, CONSTRAINT "REL_592fd05714cf23b3deb2ac911c" UNIQUE ("bookCoverImageId"), CONSTRAINT "REL_0d8a0fde3d375a9714f6efea0f" UNIQUE ("profileId"), CONSTRAINT "REL_21be7d27b00afb19a354cf6d43" UNIQUE ("universityCardId"), CONSTRAINT "REL_00bb9d5ed84b3a2f695399a129" UNIQUE ("adminProfileId"), CONSTRAINT "REL_3f74f41a5a18f1e7638a84c0ab" UNIQUE ("libraryProfileId"), CONSTRAINT "REL_c8ebb78787213afc09f6a1325d" UNIQUE ("employeePicId"), CONSTRAINT "REL_8eb99600886c9c1327b1d939f7" UNIQUE ("employeePanId"), CONSTRAINT "REL_9eca7c1e2bdd62705178d6acea" UNIQUE ("employeeCitizenshipId"), CONSTRAINT "REL_2229cacced76996778a98d7fa9" UNIQUE ("genreId"), CONSTRAINT "REL_442eca5123705b2f8af27d5f06" UNIQUE ("categoryId"), CONSTRAINT "PK_f4e0fcac36e050de337b670d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."admin_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'REJECTED')`);
        await queryRunner.query(`CREATE TYPE "public"."admin_role_enum" AS ENUM('SUDO_ADMIN', 'ADMIN', 'USER', 'STUDENT', 'LIBRARY_EMP', 'LIBRARY_ADMIN')`);
        await queryRunner.query(`CREATE TYPE "public"."admin_blocked_enum" AS ENUM('BLOCKED', 'ACTIVE')`);
        await queryRunner.query(`CREATE TABLE "admin" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "first_name" character varying NOT NULL, "middle_name" character varying, "last_name" character varying NOT NULL, "phone_number" character varying NOT NULL, "status" "public"."admin_status_enum" NOT NULL DEFAULT 'PENDING', "role" "public"."admin_role_enum" NOT NULL DEFAULT 'USER', "blocked" "public"."admin_blocked_enum" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_e032310bcef831fb83101899b10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."auth_blocked_enum" AS ENUM('BLOCKED', 'ACTIVE')`);
        await queryRunner.query(`CREATE TABLE "auth" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "email" character varying NOT NULL, "password" character varying, "firebaseId" character varying, "blocked" "public"."auth_blocked_enum" NOT NULL DEFAULT 'ACTIVE', "isEmailVerified" boolean NOT NULL DEFAULT false, "userId" uuid, "adminId" uuid, "libraryId" uuid, "libraryEmpId" uuid, CONSTRAINT "UQ_b54f616411ef3824f6a5c06ea46" UNIQUE ("email"), CONSTRAINT "REL_373ead146f110f04dad6084815" UNIQUE ("userId"), CONSTRAINT "REL_32fb476c6439a23c549fc4e45e" UNIQUE ("adminId"), CONSTRAINT "REL_d61980cd63eae0b4712943cd5b" UNIQUE ("libraryId"), CONSTRAINT "REL_8c59e970256df50176adf92f79" UNIQUE ("libraryEmpId"), CONSTRAINT "PK_7e416cf6172bc5aec04244f6459" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."library_role_enum" AS ENUM('SUDO_ADMIN', 'ADMIN', 'USER', 'STUDENT', 'LIBRARY_EMP', 'LIBRARY_ADMIN')`);
        await queryRunner.query(`CREATE TABLE "library" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "library_name" character varying NOT NULL, "library_description" character varying NOT NULL, "phone_number" character varying NOT NULL, "city" character varying NOT NULL, "street" character varying NOT NULL, "state" character varying NOT NULL, "role" "public"."library_role_enum" NOT NULL DEFAULT 'LIBRARY_ADMIN', CONSTRAINT "PK_3a61ae2e897d9b5a59a64e91aa4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."borrow_request_status_enum" AS ENUM('BORROWED', 'RETURNED', 'PENDING', 'REJECTED', 'LATE', 'OVERDUE')`);
        await queryRunner.query(`CREATE TABLE "borrow_request" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "startDate" character varying NOT NULL, "endDate" character varying NOT NULL, "status" "public"."borrow_request_status_enum" NOT NULL DEFAULT 'PENDING', "book_id" uuid, "user_id" uuid, "library_id" uuid, CONSTRAINT "PK_ead119ab91cdfd75fbde173c701" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."bill_status_enum" AS ENUM('unpaid', 'paid', 'canceled')`);
        await queryRunner.query(`CREATE TABLE "bill" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "startDate" date NOT NULL, "endDate" date NOT NULL, "daysBorrowed" integer NOT NULL, "pricePerDay" numeric(10,2) NOT NULL, "totalAmount" numeric(10,2) NOT NULL, "penaltyAmount" numeric(10,2) NOT NULL DEFAULT '0', "grandTotal" numeric(10,2) NOT NULL, "status" "public"."bill_status_enum" NOT NULL DEFAULT 'unpaid', "borrow_request_id" uuid, "user_id" uuid, "book_id" uuid, "library_id" uuid, CONSTRAINT "REL_9b3f41fd518e072864eadc4248" UNIQUE ("borrow_request_id"), CONSTRAINT "PK_683b47912b8b30fe71d1fa22199" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "book" ("id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "title" character varying NOT NULL, "slug" character varying NOT NULL, "author" character varying NOT NULL, "coverColor" character varying NOT NULL, "description" character varying NOT NULL, "totalCopies" integer NOT NULL, "price" numeric(10,2) NOT NULL, "availableCopies" integer NOT NULL, "videoUrlNeplai" character varying, "videoUrlEnglish" character varying, "videoUrlHindi" character varying, "summary" character varying NOT NULL, "libraryId" uuid, CONSTRAINT "UQ_60c46d3dac95598328e5830e2dc" UNIQUE ("slug"), CONSTRAINT "PK_a3afef72ec8f80e6e5c310b28a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wishlist" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "bookId" uuid NOT NULL, CONSTRAINT "UQ_7d30aded5099e1cfe849cc0152e" UNIQUE ("userId", "bookId"), CONSTRAINT "PK_620bff4a240d66c357b5d820eaa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rating" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "bookId" uuid, "userId" uuid, CONSTRAINT "PK_ecda8ad32645327e4765b43649e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auth_otps" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "otp" character varying NOT NULL, "expireAt" TIMESTAMP WITH TIME ZONE NOT NULL, "authId" uuid, CONSTRAINT "PK_b486cc6a733e8caa0e8f1bd0ca2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "book_genre" ("bookId" uuid NOT NULL, "genreId" uuid NOT NULL, CONSTRAINT "PK_95506c23c671010ca6bb05360e0" PRIMARY KEY ("bookId", "genreId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d3446a42df5e6f8158a5bd10f1" ON "book_genre" ("bookId") `);
        await queryRunner.query(`CREATE INDEX "IDX_564b744154ba1b5bc35e851f8b" ON "book_genre" ("genreId") `);
        await queryRunner.query(`CREATE TABLE "book_category" ("bookId" uuid NOT NULL, "categoryId" uuid NOT NULL, CONSTRAINT "PK_13a288a34083a35708212ef2b78" PRIMARY KEY ("bookId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0bf2d533812e804a640c5cefed" ON "book_category" ("bookId") `);
        await queryRunner.query(`CREATE INDEX "IDX_13d00658c3f9b8c7b8c3e3a9f3" ON "book_category" ("categoryId") `);
        await queryRunner.query(`ALTER TABLE "library_emp" ADD CONSTRAINT "FK_4fab26a97345bc3f22418a4ba1b" FOREIGN KEY ("libraryId") REFERENCES "library"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_request" ADD CONSTRAINT "FK_595acf7a0adce0a66bfeb554ee3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_592fd05714cf23b3deb2ac911cb" FOREIGN KEY ("bookCoverImageId") REFERENCES "book"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_0d8a0fde3d375a9714f6efea0fa" FOREIGN KEY ("profileId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_21be7d27b00afb19a354cf6d43a" FOREIGN KEY ("universityCardId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_00bb9d5ed84b3a2f695399a129e" FOREIGN KEY ("adminProfileId") REFERENCES "admin"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_3f74f41a5a18f1e7638a84c0ab3" FOREIGN KEY ("libraryProfileId") REFERENCES "library"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_c8ebb78787213afc09f6a1325d7" FOREIGN KEY ("employeePicId") REFERENCES "library_emp"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_8eb99600886c9c1327b1d939f7d" FOREIGN KEY ("employeePanId") REFERENCES "library_emp"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_9eca7c1e2bdd62705178d6acea1" FOREIGN KEY ("employeeCitizenshipId") REFERENCES "library_emp"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_2229cacced76996778a98d7fa9e" FOREIGN KEY ("genreId") REFERENCES "genre"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_442eca5123705b2f8af27d5f065" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_373ead146f110f04dad60848154" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_32fb476c6439a23c549fc4e45e7" FOREIGN KEY ("adminId") REFERENCES "admin"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_d61980cd63eae0b4712943cd5b3" FOREIGN KEY ("libraryId") REFERENCES "library"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_8c59e970256df50176adf92f790" FOREIGN KEY ("libraryEmpId") REFERENCES "library_emp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD CONSTRAINT "FK_1a145eba3386ce298d1125625db" FOREIGN KEY ("book_id") REFERENCES "book"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD CONSTRAINT "FK_9ca856585267cb549ce274b4c39" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD CONSTRAINT "FK_c2a4ffca483b42d743b708a14f4" FOREIGN KEY ("library_id") REFERENCES "library"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bill" ADD CONSTRAINT "FK_9b3f41fd518e072864eadc42488" FOREIGN KEY ("borrow_request_id") REFERENCES "borrow_request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bill" ADD CONSTRAINT "FK_34e537d6261c55286aa58921ada" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bill" ADD CONSTRAINT "FK_a8effa73089d64de4949d8b011f" FOREIGN KEY ("book_id") REFERENCES "book"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bill" ADD CONSTRAINT "FK_21a5ab8c19ed72c7747d54b2789" FOREIGN KEY ("library_id") REFERENCES "library"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book" ADD CONSTRAINT "FK_da052b08a5b50d4601bb0f15ac0" FOREIGN KEY ("libraryId") REFERENCES "library"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist" ADD CONSTRAINT "FK_f6eeb74a295e2aad03b76b0ba87" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist" ADD CONSTRAINT "FK_7bb20c471dc1f024c5da64ac9a9" FOREIGN KEY ("bookId") REFERENCES "book"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rating" ADD CONSTRAINT "FK_2ab7f7fc5b63b0147591ba69032" FOREIGN KEY ("bookId") REFERENCES "book"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rating" ADD CONSTRAINT "FK_a6c53dfc89ba3188b389ef29a62" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_otps" ADD CONSTRAINT "FK_8df06ead2333050a3a3414869b9" FOREIGN KEY ("authId") REFERENCES "auth"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_genre" ADD CONSTRAINT "FK_d3446a42df5e6f8158a5bd10f1a" FOREIGN KEY ("bookId") REFERENCES "book"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "book_genre" ADD CONSTRAINT "FK_564b744154ba1b5bc35e851f8bc" FOREIGN KEY ("genreId") REFERENCES "genre"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_category" ADD CONSTRAINT "FK_0bf2d533812e804a640c5cefed8" FOREIGN KEY ("bookId") REFERENCES "book"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "book_category" ADD CONSTRAINT "FK_13d00658c3f9b8c7b8c3e3a9f3e" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "book_category" DROP CONSTRAINT "FK_13d00658c3f9b8c7b8c3e3a9f3e"`);
        await queryRunner.query(`ALTER TABLE "book_category" DROP CONSTRAINT "FK_0bf2d533812e804a640c5cefed8"`);
        await queryRunner.query(`ALTER TABLE "book_genre" DROP CONSTRAINT "FK_564b744154ba1b5bc35e851f8bc"`);
        await queryRunner.query(`ALTER TABLE "book_genre" DROP CONSTRAINT "FK_d3446a42df5e6f8158a5bd10f1a"`);
        await queryRunner.query(`ALTER TABLE "auth_otps" DROP CONSTRAINT "FK_8df06ead2333050a3a3414869b9"`);
        await queryRunner.query(`ALTER TABLE "rating" DROP CONSTRAINT "FK_a6c53dfc89ba3188b389ef29a62"`);
        await queryRunner.query(`ALTER TABLE "rating" DROP CONSTRAINT "FK_2ab7f7fc5b63b0147591ba69032"`);
        await queryRunner.query(`ALTER TABLE "wishlist" DROP CONSTRAINT "FK_7bb20c471dc1f024c5da64ac9a9"`);
        await queryRunner.query(`ALTER TABLE "wishlist" DROP CONSTRAINT "FK_f6eeb74a295e2aad03b76b0ba87"`);
        await queryRunner.query(`ALTER TABLE "book" DROP CONSTRAINT "FK_da052b08a5b50d4601bb0f15ac0"`);
        await queryRunner.query(`ALTER TABLE "bill" DROP CONSTRAINT "FK_21a5ab8c19ed72c7747d54b2789"`);
        await queryRunner.query(`ALTER TABLE "bill" DROP CONSTRAINT "FK_a8effa73089d64de4949d8b011f"`);
        await queryRunner.query(`ALTER TABLE "bill" DROP CONSTRAINT "FK_34e537d6261c55286aa58921ada"`);
        await queryRunner.query(`ALTER TABLE "bill" DROP CONSTRAINT "FK_9b3f41fd518e072864eadc42488"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP CONSTRAINT "FK_c2a4ffca483b42d743b708a14f4"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP CONSTRAINT "FK_9ca856585267cb549ce274b4c39"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP CONSTRAINT "FK_1a145eba3386ce298d1125625db"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_8c59e970256df50176adf92f790"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_d61980cd63eae0b4712943cd5b3"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_32fb476c6439a23c549fc4e45e7"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_373ead146f110f04dad60848154"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_442eca5123705b2f8af27d5f065"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_2229cacced76996778a98d7fa9e"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_9eca7c1e2bdd62705178d6acea1"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_8eb99600886c9c1327b1d939f7d"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_c8ebb78787213afc09f6a1325d7"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_3f74f41a5a18f1e7638a84c0ab3"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_00bb9d5ed84b3a2f695399a129e"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_21be7d27b00afb19a354cf6d43a"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_0d8a0fde3d375a9714f6efea0fa"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_592fd05714cf23b3deb2ac911cb"`);
        await queryRunner.query(`ALTER TABLE "role_request" DROP CONSTRAINT "FK_595acf7a0adce0a66bfeb554ee3"`);
        await queryRunner.query(`ALTER TABLE "library_emp" DROP CONSTRAINT "FK_4fab26a97345bc3f22418a4ba1b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13d00658c3f9b8c7b8c3e3a9f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0bf2d533812e804a640c5cefed"`);
        await queryRunner.query(`DROP TABLE "book_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_564b744154ba1b5bc35e851f8b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3446a42df5e6f8158a5bd10f1"`);
        await queryRunner.query(`DROP TABLE "book_genre"`);
        await queryRunner.query(`DROP TABLE "auth_otps"`);
        await queryRunner.query(`DROP TABLE "rating"`);
        await queryRunner.query(`DROP TABLE "wishlist"`);
        await queryRunner.query(`DROP TABLE "book"`);
        await queryRunner.query(`DROP TABLE "bill"`);
        await queryRunner.query(`DROP TYPE "public"."bill_status_enum"`);
        await queryRunner.query(`DROP TABLE "borrow_request"`);
        await queryRunner.query(`DROP TYPE "public"."borrow_request_status_enum"`);
        await queryRunner.query(`DROP TABLE "library"`);
        await queryRunner.query(`DROP TYPE "public"."library_role_enum"`);
        await queryRunner.query(`DROP TABLE "auth"`);
        await queryRunner.query(`DROP TYPE "public"."auth_blocked_enum"`);
        await queryRunner.query(`DROP TABLE "admin"`);
        await queryRunner.query(`DROP TYPE "public"."admin_blocked_enum"`);
        await queryRunner.query(`DROP TYPE "public"."admin_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."admin_status_enum"`);
        await queryRunner.query(`DROP TABLE "media"`);
        await queryRunner.query(`DROP TYPE "public"."media_mediatype_enum"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP TABLE "role_request"`);
        await queryRunner.query(`DROP TABLE "library_emp"`);
        await queryRunner.query(`DROP TYPE "public"."library_emp_role_enum"`);
        await queryRunner.query(`DROP TABLE "genre"`);
        await queryRunner.query(`DROP TABLE "category"`);
    }

}
