import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1769186376772 implements MigrationInterface {
    name = 'AutoMigration1769186376772'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_8c59e970256df50176adf92f790"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_d61980cd63eae0b4712943cd5b3"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_32fb476c6439a23c549fc4e45e7"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_373ead146f110f04dad60848154"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP CONSTRAINT "FK_13d3ec0991aa45a896d56f377b1"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP CONSTRAINT "FK_c2a4ffca483b42d743b708a14f4"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP CONSTRAINT "FK_9ca856585267cb549ce274b4c39"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP CONSTRAINT "FK_1a145eba3386ce298d1125625db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_UNIVERSITY_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUTH_USER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUTH_ADMIN_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUTH_LIBRARY_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUTH_LIBRARY_EMP_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUTH_BLOCKED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUTH_DELETED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BR_BILL_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BR_DELETED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BR_END_DATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BR_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BR_LIBRARY_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BR_BOOK_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BR_USER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOOK_DELETED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOOK_AVAILABLE_COPIES"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOOK_PRICE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOOK_AUTHOR"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOOK_LIBRARY_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WISHLIST_USER_BOOK"`);
        await queryRunner.query(`CREATE TABLE "role_request" ("id" uuid NOT NULL, "last_activity_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "requested_role" character varying NOT NULL, "status" character varying NOT NULL, "reason" character varying NOT NULL, "userId" uuid, CONSTRAINT "PK_56e5c87e0e09b2416e398992a88" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "genre" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "genre" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "library_emp" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "library_emp" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "admin" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "admin" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "library" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "library" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP CONSTRAINT "UQ_13d3ec0991aa45a896d56f377b1"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP COLUMN "bill_id"`);
        await queryRunner.query(`ALTER TABLE "bill" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "bill" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "wishlist" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "wishlist" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "rating" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "rating" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "auth_otps" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "auth_otps" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "auth" ADD "signupToken" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "auth" ADD "signupTokenExpiresAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "UQ_f7d8db89361716a255bec8700c7"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD "startDate" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD "endDate" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "book" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "book" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "book" DROP COLUMN "summary"`);
        await queryRunner.query(`ALTER TABLE "book" ADD "summary" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role_request" ADD CONSTRAINT "FK_595acf7a0adce0a66bfeb554ee3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_373ead146f110f04dad60848154" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_32fb476c6439a23c549fc4e45e7" FOREIGN KEY ("adminId") REFERENCES "admin"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_d61980cd63eae0b4712943cd5b3" FOREIGN KEY ("libraryId") REFERENCES "library"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_8c59e970256df50176adf92f790" FOREIGN KEY ("libraryEmpId") REFERENCES "library_emp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD CONSTRAINT "FK_1a145eba3386ce298d1125625db" FOREIGN KEY ("book_id") REFERENCES "book"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD CONSTRAINT "FK_9ca856585267cb549ce274b4c39" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD CONSTRAINT "FK_c2a4ffca483b42d743b708a14f4" FOREIGN KEY ("library_id") REFERENCES "library"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP CONSTRAINT "FK_c2a4ffca483b42d743b708a14f4"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP CONSTRAINT "FK_9ca856585267cb549ce274b4c39"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP CONSTRAINT "FK_1a145eba3386ce298d1125625db"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_8c59e970256df50176adf92f790"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_d61980cd63eae0b4712943cd5b3"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_32fb476c6439a23c549fc4e45e7"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_373ead146f110f04dad60848154"`);
        await queryRunner.query(`ALTER TABLE "role_request" DROP CONSTRAINT "FK_595acf7a0adce0a66bfeb554ee3"`);
        await queryRunner.query(`ALTER TABLE "book" DROP COLUMN "summary"`);
        await queryRunner.query(`ALTER TABLE "book" ADD "summary" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "book" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "book" ADD "description" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD "endDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "borrow_request" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD "startDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "UQ_f7d8db89361716a255bec8700c7" UNIQUE ("firebaseId")`);
        await queryRunner.query(`ALTER TABLE "auth" DROP COLUMN "signupTokenExpiresAt"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP COLUMN "signupToken"`);
        await queryRunner.query(`ALTER TABLE "auth_otps" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "auth_otps" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "rating" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "rating" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wishlist" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "wishlist" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bill" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "bill" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD "bill_id" uuid`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD CONSTRAINT "UQ_13d3ec0991aa45a896d56f377b1" UNIQUE ("bill_id")`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "library" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "library" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "auth" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "auth" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "admin" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "admin" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "media" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "media" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "library_emp" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "library_emp" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "genre" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "genre" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "category" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "category" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP TABLE "role_request"`);
        await queryRunner.query(`CREATE INDEX "IDX_WISHLIST_USER_BOOK" ON "wishlist" ("userId", "bookId") `);
        await queryRunner.query(`CREATE INDEX "IDX_BOOK_LIBRARY_ID" ON "book" ("libraryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_BOOK_AUTHOR" ON "book" ("author") `);
        await queryRunner.query(`CREATE INDEX "IDX_BOOK_PRICE" ON "book" ("price") `);
        await queryRunner.query(`CREATE INDEX "IDX_BOOK_AVAILABLE_COPIES" ON "book" ("availableCopies") `);
        await queryRunner.query(`CREATE INDEX "IDX_BOOK_DELETED_AT" ON "book" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_BR_USER_ID" ON "borrow_request" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_BR_BOOK_ID" ON "borrow_request" ("book_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_BR_LIBRARY_ID" ON "borrow_request" ("library_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_BR_STATUS" ON "borrow_request" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_BR_END_DATE" ON "borrow_request" ("endDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_BR_DELETED_AT" ON "borrow_request" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_BR_BILL_ID" ON "borrow_request" ("bill_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUTH_DELETED_AT" ON "auth" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUTH_BLOCKED" ON "auth" ("blocked") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUTH_LIBRARY_EMP_ID" ON "auth" ("libraryEmpId") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUTH_LIBRARY_ID" ON "auth" ("libraryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUTH_ADMIN_ID" ON "auth" ("adminId") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUTH_USER_ID" ON "auth" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_UNIVERSITY_ID" ON "user" ("university_id") `);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD CONSTRAINT "FK_1a145eba3386ce298d1125625db" FOREIGN KEY ("book_id") REFERENCES "book"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD CONSTRAINT "FK_9ca856585267cb549ce274b4c39" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD CONSTRAINT "FK_c2a4ffca483b42d743b708a14f4" FOREIGN KEY ("library_id") REFERENCES "library"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "borrow_request" ADD CONSTRAINT "FK_13d3ec0991aa45a896d56f377b1" FOREIGN KEY ("bill_id") REFERENCES "bill"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_373ead146f110f04dad60848154" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_32fb476c6439a23c549fc4e45e7" FOREIGN KEY ("adminId") REFERENCES "admin"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_d61980cd63eae0b4712943cd5b3" FOREIGN KEY ("libraryId") REFERENCES "library"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_8c59e970256df50176adf92f790" FOREIGN KEY ("libraryEmpId") REFERENCES "library_emp"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
