export enum SIGNUPSTATUS {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
}

export enum ROLES {
  SUDO_ADMIN = "SUDO_ADMIN",
  ADMIN = "ADMIN",
  USER = "USER",
  STUDENT = "STUDENT",
  LIBRARY_EMP = "LIBRARY_EMP",
  LIBRARY_ADMIN = "LIBRARY_ADMIN",
}

export enum BLOCK_STATUS {
  BLOCKED = "BLOCKED",
  ACTIVE = "ACTIVE",
}

export enum BORROWER_STATUS {
  BORROWED = "BORROWED",
  RETURNED = "RETURNED",
  PENDING = "PENDING",
  REJECTED = "REJECTED",
  LATE = "LATE",
  OVERDUE = "OVERDUE",
}

export enum BILL_STATUS {
  UNPAID = "unpaid",
  PAID = "paid",
  CANCELED = "canceled",
}

export enum STATUS_CODE {
  SUCCESS = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
  SESSION_EXPIRED = 401,
}

export enum MEDIA_TYPE {
  PROFILE = "PROFILE",
  UNIVERSITY_CARD = "UNIVERSITY_CARD",
  BOOK = "BOOK",
  COVER_IMAGE = "COVER_IMAGE",
  GENRE_PIC = "GENRE_PIC",
  CATEGORY_PIC = "CATEGORY_PIC",
  EMPLOYEE_CONTRACT = "EMPLOYEE_CONTRACT",
  EMPLOYEE_PAN = "EMPLOYEE_PAN",
  EMPLOYEE_CITIZENSHIP = "EMPLOYEE_CITIZENSHIP",
}

export const BookGenres = {
  FANTASY: "FANTASY",
  ROMANCE: "ROMANCE",
  THRILLER: "THRILLER",
  MYSTERY: "MYSTERY",
  SCIFI: "SCIFI",
  BIOGRAPHY: "BIOGRAPHY",
};

export enum OTP_TYPE {
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  PASSWORD_RESET = "PASSWORD_RESET",
  SIGN_UP = "SIGN_UP",
}


